//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// SCDeskTools.rc에서 사용
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_SCDESKTOOLS_DIALOG				102

#define ID_TOOL_COLOR_PICKER			32771
#define ID_TOOL_DROPPER					32772
#define ID_TOOL_CAPTURE_WINDOW			32773
#define ID_TOOL_CAPTURE_REGION			32774
#define ID_APP_SHOW_HIDE				32775
#define ID_HELP_ABOUT					32776
#define ID_SC_EXIT						32777
#define ID_TOOL_PASTE_CLIPBOARD			32778
#define ID_TOOL_PROTRACTOR				32779
#define ID_TOOL_RULER					32780
#define ID_TOOL_CAPTURE_FULLSCREEN		32781
#define ID_TOOL_CAPTURE_FREEHAND		32782

//모니터별 캡처 — 멀티 모니터 환경에서 동적 메뉴 항목용 ID 범위. 16 모니터까지.
#define ID_TOOL_CAPTURE_MONITOR_FIRST	32800
#define ID_TOOL_CAPTURE_MONITOR_LAST	32815

// 다음은 새 개체에 사용할 기본값입니다.
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32817
#endif
#endif
